# docker-compose.yml
# $ docker compose up -d --build

version: "3.9"

name: klines-service

networks:
  grindurus:
    external: true

services:
  db:
    image: timescale/timescaledb:latest-pg18
    container_name: klines-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/home/postgres/data
    networks:
      - grindurus
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 3s
      timeout: 5s
      retries: 15

  api:
    build: .
    container_name: klines-api
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app
    networks:
      - grindurus
    depends_on:
      db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.docker.network=grindurus
      
      # --- localhost HTTPS ---
      - traefik.http.routers.api-localhost.rule=Host(`klines.localhost`)
      - traefik.http.routers.api-localhost.tls=true
      - traefik.http.routers.api-localhost.entrypoints=websecure

      # --- prod HTTPS ---
      - traefik.http.routers.api.rule=Host(`klines.grindurus.xyz`)
      - traefik.http.routers.api.tls.certresolver=le
      - traefik.http.routers.api.entrypoints=websecure

      # --- general backend ---
      - traefik.http.services.api.loadbalancer.server.port=8000

volumes:
  pgdata: