name: Deploy Klines

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }} # server ipv4 address
          username: ${{ secrets.SERVER_USER }} # root
          key: ${{ secrets.SSH_KEY }} # ssh private key 
          script: |
            cd /opt/grindurus-klines-service
            git pull
            docker compose up -d --build